// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwLr91ySdUQyGzA6LExQ5ryvzh31lMIw',
    appId: '1:797468589410:android:79e0481e97b1dc431d003b',
    messagingSenderId: '797468589410',
    projectId: 'atithibhoj-app',
    storageBucket: 'atithibhoj-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgtuVu3w8XoyXlWWoejwbGD_n4VmtRfmc',
    appId: '1:797468589410:ios:651ff0ee61bf6c4a1d003b',
    messagingSenderId: '797468589410',
    projectId: 'atithibhoj-app',
    storageBucket: 'atithibhoj-app.firebasestorage.app',
    androidClientId: '797468589410-5pjmvheodakl07dsc2884bs9emrlfhro.apps.googleusercontent.com',
    iosClientId: '797468589410-0mbhb18bgullkrh6qtf2tq66ijie6c5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiffinServiceApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpIlkWbU0nNHH6uGWWnxuhRKzOM5ANnNk',
    appId: '1:797468589410:web:cbbbaaf811b356081d003b',
    messagingSenderId: '797468589410',
    projectId: 'atithibhoj-app',
    authDomain: 'atithibhoj-app.firebaseapp.com',
    storageBucket: 'atithibhoj-app.firebasestorage.app',
    measurementId: 'G-D5F17DB44C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgtuVu3w8XoyXlWWoejwbGD_n4VmtRfmc',
    appId: '1:797468589410:ios:651ff0ee61bf6c4a1d003b',
    messagingSenderId: '797468589410',
    projectId: 'atithibhoj-app',
    storageBucket: 'atithibhoj-app.firebasestorage.app',
    androidClientId: '797468589410-5pjmvheodakl07dsc2884bs9emrlfhro.apps.googleusercontent.com',
    iosClientId: '797468589410-0mbhb18bgullkrh6qtf2tq66ijie6c5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiffinServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpIlkWbU0nNHH6uGWWnxuhRKzOM5ANnNk',
    appId: '1:797468589410:web:9b6d7642237009761d003b',
    messagingSenderId: '797468589410',
    projectId: 'atithibhoj-app',
    authDomain: 'atithibhoj-app.firebaseapp.com',
    storageBucket: 'atithibhoj-app.firebasestorage.app',
    measurementId: 'G-JBBED9C6XZ',
  );
}
